In [1]:
import jax
import jax.numpy as jnp

import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath("./")))))

from jaxmeta.grad import *

In [13]:
def f1(x, y):
	return y**2

def f2(x, y):
	return y+1

df1 = jacobian_fn(f1)

def f3(x, y):
	df1_ = df1(x, y)
	y2 = f2(x, y)
	return df1_*y2

df3 = jacobian_fn(f3)

In [8]:
x = jnp.array([[1.0], [2.0]])

In [9]:
f1(None, x)

DeviceArray([[1.],
             [4.]], dtype=float32)

In [10]:
f2(None, x)

DeviceArray([[2.],
             [3.]], dtype=float32)

In [11]:
f3(None, x)

DeviceArray([[ 4.],
             [12.]], dtype=float32)

In [16]:
df3(None, x)[:, 0]

DeviceArray([[ 6.],
             [10.]], dtype=float32)